clean:
	rm -f *.o *.elf *.map payload_src/*.o lv2/src/*.o lv1/src/*.o *.bin
all:
	make -f Makefile_4.21D clean --no-print-directory
	make -f Makefile_4.21D --no-print-directory
	make -f Makefile_4.30D clean --no-print-directory
	make -f Makefile_4.30D --no-print-directory
	make -f Makefile_4.41D clean --no-print-directory
	make -f Makefile_4.41D --no-print-directory
	make -f Makefile_4.46D clean --no-print-directory
	make -f Makefile_4.46D --no-print-directory
	make -f Makefile_4.50D clean --no-print-directory
	make -f Makefile_4.50D --no-print-directory
	make -f Makefile_4.53D clean --no-print-directory
	make -f Makefile_4.53D --no-print-directory
	make -f Makefile_4.55D clean --no-print-directory
	make -f Makefile_4.55D --no-print-directory
	make -f Makefile_4.60D clean --no-print-directory
	make -f Makefile_4.60D --no-print-directory
	make -f Makefile_4.65D clean --no-print-directory
	make -f Makefile_4.65D --no-print-directory
	make -f Makefile_4.66D clean --no-print-directory
	make -f Makefile_4.66D --no-print-directory
	make -f Makefile_4.70D clean --no-print-directory
	make -f Makefile_4.70D --no-print-directory
	make -f Makefile_4.75D clean --no-print-directory
	make -f Makefile_4.75D --no-print-directory
	make -f Makefile_4.76D clean --no-print-directory
	make -f Makefile_4.76D --no-print-directory
	make -f Makefile_4.78D clean --no-print-directory
	make -f Makefile_4.78D --no-print-directory
	make -f Makefile_4.80D clean --no-print-directory
	make -f Makefile_4.80D --no-print-directory
	rm -f *.o *.elf *.map payload_src/*.o lv2/src/*.o lv1/src/*.o
